---
id: introduction-japanese
base_name: about-oss-gate
tags:
- rabbit
- oss_gate
presentation_date: 2016-08-22
version: 2016.8.22.3
licenses:
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: OSS Gate
  email: kou+oss-gate@cozmixng.org
  rubygems_user: oss-gate
  slideshare_user: 
  speaker_deck_user: 
