---
id: introduction-japanese
base_name: about-oss-gate
tags:
- rabbit
- oss_gate
presentation_date: 2017-10-14
version: 2017.10.14.1
licenses:
- CC-BY-SA-4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: OSS Gate
  email: kou+oss-gate@cozmixng.org
  rubygems_user: oss-gate
  slideshare_user: 
  speaker_deck_user: 
